In [1]:
from job_agents.extract_skills import extract_skills

In [2]:
job = """Applications are accepted until further notice. 
Please note this posting is to advertise potential job opportunities. 
This exact role may not be open today but could open in the near future.
When you apply, a Cisco representative may contact you directly if a relevant position opens. 
Meet the team 
We are a dynamic, diverse, and distributed team dedicated to innovating and redefining Cisco IT! 
Our team impacts thousands of Cisco employees by providing opportunities for innovation and accelerating the adoption of modern engineering practices, which improves the speed of product development. 
We champion emerging architectures, excellence in software development, and innovation, all within a synergetic and can-do culture. 
You will collaborate with small, forward-thinking teams that focus on common problems across domains, resulting in diverse technical challenges and accelerated career growth. 
You will engage with senior engineers, developers, and DevOps teams to uphold high system availability and strengthens software delivery processes. 
Your impact
You are a proactive problem-solver who thrives on collaboration, bringing strong teamwork and communication skills to every project. 
Adaptable and comfortable in diverse, fast-paced environments, you are always eager to learn and contribute meaningfully to ongoing initiatives. 
With a commitment to excellence and innovation in software development, you are dedicated to making a positive impact and growing alongside my team.  
As a Technical Systems Engineer, you will assist in maintaining and optimizing the development, testing, and production environments by providing operational support, troubleshooting issues, and ensuring the availability and performance of systems. 
Provide guidance to junior engineers as needed. 
Application and System Support: 
Assist in monitoring, troubleshooting, and resolving issues across development, staging, and production environments. 
Support the deployment pipeline to ensure seamless automation and application deployments. 
Collaborate with the DevOps team to uphold high availability, stability, and performance of applications and services. 
Incident Management: 
Monitor production systems for issues or outages and respond promptly to alerts. 
Troubleshoot, isolate, and resolve incidents. 
Document issues, solutions, and preventive measures in knowledge bases or incident reports. 
Collaboration with Development and Operations Teams: 
Facilitate collaboration between development and operations teams to improve software delivery processes and ensure efficient production systems. 
Participate in daily stand-ups and project meetings, learning from senior team members and contributing to ongoing work. 
Automation Support: 
Assist in implementing, monitoring, and maintaining continuous integration and continuous deployment (CI/CD) pipelines. 
Work on automation requirements for tools such as Jenkins, GitHub, SonarQube, Artifactory, etc. 
Minimum Qualifications 
A technical undergraduate degree with 2 years of relevant practical experience in DevOps, IT support, or a related technical field or a recent graduate/ in final year of a technical Master’s degree. 
Familiarity with version control systems like Git. 
Strong understanding of CI/CD principles and tools (e.g., Jenkins, GitLab CI, CircleCI). 
Familiarity with cloud platforms (OpenShift, AWS, Azure, Google Cloud) or virtualization technologies (Docker, Podman, VMware). 
Preferred Qualifications 
Basic knowledge of case management and problem management using ServiceNow. 
Exposure to monitoring tools (e.g., ThousandEyes, Prometheus, Grafana, Nagios). 
Knowledge management for application support. 
Exposure to Agile methodologies and collaboration tools like JIRA or Confluence. 
Why Cisco 
At Cisco, we’re revolutionizing how data and infrastructure connect and protect organizations in the AI era – and beyond. 
We’ve been innovating fearlessly for 40 years to create solutions that power how humans and technology work together across the physical and digital worlds. 
These solutions provide customers with unparalleled security, visibility, and insights across the entire digital footprint. 
Simply put – we power the future.  
Fueled by the depth and breadth of our technology, we experiment and create meaningful solutions. 
Add to that our worldwide network of doers and experts, and you’ll see that the opportunities to grow and build are limitless. 
We work as a team, collaborating with empathy to make really big things happen on a global scale. 
Because our solutions are everywhere, our impact is everywhere.  
We are Cisco, and our power starts with you. """

In [3]:
texts = job.split("\n")

In [28]:
input_samples = []
for i,t in enumerate(texts):
    input_samples.append(
        {
            "input id": str(i),
            "text": t
        }
    )

In [29]:
input_samples

[{'input id': '0', 'text': 'Applications are accepted until further notice. '},
 {'input id': '1',
  'text': 'Please note this posting is to advertise potential job opportunities. '},
 {'input id': '2',
  'text': 'This exact role may not be open today but could open in the near future.'},
 {'input id': '3',
  'text': 'When you apply, a Cisco representative may contact you directly if a relevant position opens. '},
 {'input id': '4', 'text': 'Meet the team '},
 {'input id': '5',
  'text': 'We are a dynamic, diverse, and distributed team dedicated to innovating and redefining Cisco IT! '},
 {'input id': '6',
  'text': 'Our team impacts thousands of Cisco employees by providing opportunities for innovation and accelerating the adoption of modern engineering practices, which improves the speed of product development. '},
 {'input id': '7',
  'text': 'We champion emerging architectures, excellence in software development, and innovation, all within a synergetic and can-do culture. '},
 {'input id': '8',
  'text': 'You will collaborate with small, forward-thinking teams that focus on common problems across domains, resulting in diverse technical challenges and accelerated career growth. '},
 {'input id': '9',
  'text': 'You will engage with senior engineers, developers, and DevOps teams to uphold high system availability and strengthens software delivery processes. '},
 {'input id': '10', 'text': 'Your impact'},
 {'input id': '11',
  'text': 'You are a proactive problem-solver who thrives on collaboration, bringing strong teamwork and communication skills to every project. '},
 {'input id': '12',
  'text': 'Adaptable and comfortable in diverse, fast-paced environments, you are always eager to learn and contribute meaningfully to ongoing initiatives. '},
 {'input id': '13',
  'text': 'With a commitment to excellence and innovation in software development, you are dedicated to making a positive impact and growing alongside my team.  '},
 {'input id': '14',
  'text': 'As a Technical Systems Engineer, you will assist in maintaining and optimizing the development, testing, and production environments by providing operational support, troubleshooting issues, and ensuring the availability and performance of systems. '},
 {'input id': '15',
  'text': 'Provide guidance to junior engineers as needed. '},
 {'input id': '16', 'text': 'Application and System Support: '},
 {'input id': '17',
  'text': 'Assist in monitoring, troubleshooting, and resolving issues across development, staging, and production environments. '},
 {'input id': '18',
  'text': 'Support the deployment pipeline to ensure seamless automation and application deployments. '},
 {'input id': '19',
  'text': 'Collaborate with the DevOps team to uphold high availability, stability, and performance of applications and services. '},
 {'input id': '20', 'text': 'Incident Management: '},
 {'input id': '21',
  'text': 'Monitor production systems for issues or outages and respond promptly to alerts. '},
 {'input id': '22', 'text': 'Troubleshoot, isolate, and resolve incidents. '},
 {'input id': '23',
  'text': 'Document issues, solutions, and preventive measures in knowledge bases or incident reports. '},
 {'input id': '24',
  'text': 'Collaboration with Development and Operations Teams: '},
 {'input id': '25',
  'text': 'Facilitate collaboration between development and operations teams to improve software delivery processes and ensure efficient production systems. '},
 {'input id': '26',
  'text': 'Participate in daily stand-ups and project meetings, learning from senior team members and contributing to ongoing work. '},
 {'input id': '27', 'text': 'Automation Support: '},
 {'input id': '28',
  'text': 'Assist in implementing, monitoring, and maintaining continuous integration and continuous deployment (CI/CD) pipelines. '},
 {'input id': '29',
  'text': 'Work on automation requirements for tools such as Jenkins, GitHub, SonarQube, Artifactory, etc. '},
 {'input id': '30', 'text': 'Minimum Qualifications '},
 {'input id': '31',
  'text': 'A technical undergraduate degree with 2 years of relevant practical experience in DevOps, IT support, or a related technical field or a recent graduate/ in final year of a technical Master’s degree. '},
 {'input id': '32',
  'text': 'Familiarity with version control systems like Git. '},
 {'input id': '33',
  'text': 'Strong understanding of CI/CD principles and tools (e.g., Jenkins, GitLab CI, CircleCI). '},
 {'input id': '34',
  'text': 'Familiarity with cloud platforms (OpenShift, AWS, Azure, Google Cloud) or virtualization technologies (Docker, Podman, VMware). '},
 {'input id': '35', 'text': 'Preferred Qualifications '},
 {'input id': '36',
  'text': 'Basic knowledge of case management and problem management using ServiceNow. '},
 {'input id': '37',
  'text': 'Exposure to monitoring tools (e.g., ThousandEyes, Prometheus, Grafana, Nagios). '},
 {'input id': '38', 'text': 'Knowledge management for application support. '},
 {'input id': '39',
  'text': 'Exposure to Agile methodologies and collaboration tools like JIRA or Confluence. '},
 {'input id': '40', 'text': 'Why Cisco '},
 {'input id': '41',
  'text': 'At Cisco, we’re revolutionizing how data and infrastructure connect and protect organizations in the AI era – and beyond. '},
 {'input id': '42',
  'text': 'We’ve been innovating fearlessly for 40 years to create solutions that power how humans and technology work together across the physical and digital worlds. '},
 {'input id': '43',
  'text': 'These solutions provide customers with unparalleled security, visibility, and insights across the entire digital footprint. '},
 {'input id': '44', 'text': 'Simply put – we power the future.  '},
 {'input id': '45',
  'text': 'Fueled by the depth and breadth of our technology, we experiment and create meaningful solutions. '},
 {'input id': '46',
  'text': 'Add to that our worldwide network of doers and experts, and you’ll see that the opportunities to grow and build are limitless. '},
 {'input id': '47',
  'text': 'We work as a team, collaborating with empathy to make really big things happen on a global scale. '},
 {'input id': '48',
  'text': 'Because our solutions are everywhere, our impact is everywhere.  '},
 {'input id': '49', 'text': 'We are Cisco, and our power starts with you. '}]

In [19]:
all_skills = []
for i in range(0, len(input_samples), 5):
    print(i)
    skills = await extract_skills(str(input_samples[i:i+5]))
    all_skills += skills

0
Number of input tokens:  482
Number of output tokens:  1
5
Number of input tokens:  554
Number of output tokens:  206
10
Number of input tokens:  541
Number of output tokens:  236
15
Number of input tokens:  493
Number of output tokens:  401
20
Number of input tokens:  478
Number of output tokens:  175
25
Number of input tokens:  516
Number of output tokens:  230
30
Number of input tokens:  529
Number of output tokens:  504
35
Number of input tokens:  483
Number of output tokens:  374
40
Number of input tokens:  510
Number of output tokens:  1
45
Number of input tokens:  516
Number of output tokens:  1

In [21]:
len(all_skills)

73

In [22]:
import pandas as pd

In [27]:
df_text

    input id                                               text
0          0   Applications are accepted until further notice.
1          1  Please note this posting is to advertise poten...
2          2  This exact role may not be open today but coul...
3          3  When you apply, a Cisco representative may con...
4          4                                     Meet the team
5          5  We are a dynamic, diverse, and distributed tea...
6          6  Our team impacts thousands of Cisco employees ...
7          7  We champion emerging architectures, excellence...
8          8  You will collaborate with small, forward-think...
9          9  You will engage with senior engineers, develop...
10        10                                        Your impact
11        11  You are a proactive problem-solver who thrives...
12        12  Adaptable and comfortable in diverse, fast-pac...
13        13  With a commitment to excellence and innovation...
14        14  As a Technical Systems Engineer, you will assi...
15        15   Provide guidance to junior engineers as needed.
16        16                   Application and System Support:
17        17  Assist in monitoring, troubleshooting, and res...
18        18  Support the deployment pipeline to ensure seam...
19        19  Collaborate with the DevOps team to uphold hig...
20        20                              Incident Management:
21        21  Monitor production systems for issues or outag...
22        22     Troubleshoot, isolate, and resolve incidents.
23        23  Document issues, solutions, and preventive mea...
24        24  Collaboration with Development and Operations ...
25        25  Facilitate collaboration between development a...
26        26  Participate in daily stand-ups and project mee...
27        27                               Automation Support:
28        28  Assist in implementing, monitoring, and mainta...
29        29  Work on automation requirements for tools such...
30        30                            Minimum Qualifications
31        31  A technical undergraduate degree with 2 years ...
32        32  Familiarity with version control systems like ...
33        33  Strong understanding of CI/CD principles and t...
34        34  Familiarity with cloud platforms (OpenShift, A...
35        35                          Preferred Qualifications
36        36  Basic knowledge of case management and problem...
37        37  Exposure to monitoring tools (e.g., ThousandEy...
38        38     Knowledge management for application support.
39        39  Exposure to Agile methodologies and collaborat...
40        40                                         Why Cisco
41        41  At Cisco, we’re revolutionizing how data and i...
42        42  We’ve been innovating fearlessly for 40 years ...
43        43  These solutions provide customers with unparal...
44        44                Simply put – we power the future.
45        45  Fueled by the depth and breadth of our technol...
46        46  Add to that our worldwide network of doers and...
47        47  We work as a team, collaborating with empathy ...
48        48  Because our solutions are everywhere, our impa...
49        49      We are Cisco, and our power starts with you.

In [30]:
df_text = pd.DataFrame(input_samples)
df_skills = pd.DataFrame(all_skills)
pd.merge(left=df_skills, right=df_text, on="input id", how="left")

,input id,name,span,text
0,6,Innovation,opportunities for innovation,Our team impacts thousands of Cisco employees ...
1,6,Engineering Practices,modern engineering practices,Our team impacts thousands of Cisco employees ...
2,6,Product Development,product development,Our team impacts thousands of Cisco employees ...
3,7,Software Development,excellence in software development,"We champion emerging architectures, excellence..."
4,8,Collaboration,collaborate,"You will collaborate with small, forward-think..."
...,...,...,...,...
68,38,Knowledge Management,Knowledge management,Knowledge management for application support.
69,39,Agile Methodologies,Agile methodologies,Exposure to Agile methodologies and collaborat...
70,39,Collaboration Tools,collaboration tools,Exposure to Agile methodologies and collaborat...
71,39,JIRA,JIRA,Exposure to Agile methodologies and collaborat...
72,39,Confluence,Confluence,Exposure to Agile methodologies and collaborat...